name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Greet
        run: echo "Hello world!"
      
      - name: Test running shell scripts
        run: |
          echo "First line"
          echo "Second line"
        
